### ISSUE TITLE
Inconsistent track width generated by track width tuner

### ISSUE THREAD

**Issue by ethan-robotics** [acmerobotics/road-runner-quickstart#3] opened 2018-10-22 02:27 UTC
I am getting incorrect and inconsistent results from the track width tuner. I use a 4 wheel drive with traction in the back, and omnis in the front. When I ran the default configuration, the tuner gave a result of 13.09. The actual width is 16.25. I tried adjusting the track width to provide accurate turns. I got accurate results at a track width of 22.5. I also tried different combinations of motor power and number of turns in the track width (listed below).

Motor power | Number of turns | Output track width
------------ | ----------------- | ------------------- 
(default ) 0.3| 4 | 13.09
0.3 | 2 | 15.73
0.3 | 6 | 12.2
0.3 | 12 | 11.46
0.5 | 4 | 13.17
0.7 | 4 | 13.36

**Comment by rbrott** [comment] 2018-10-22 12:37
Duplicate of #4

**Closed by rbrott** 2018-10-22 12:37 UTC
